# Generated by Django 4.2.15 on 2024-08-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0019_auto_20231026_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='kebele_id',
            field=models.CharField(db_column='KebeleID', max_length=100, null=True),
        ),
    ]
