# Generated by Django 4.2.15 on 2024-08-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0020_insuree_kebele_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='national_id',
            field=models.CharField(db_column='NationalID', max_length=100, null=True),
        ),
    ]
