# Generated by Django 4.2.15 on 2024-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0021_insuree_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='kebele_id',
            field=models.CharField(blank=True, db_column='KebeleID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='national_id',
            field=models.CharField(blank=True, db_column='NationalID', max_length=100, null=True),
        ),
    ]
