# Generated by Django 3.2.20 on 2024-09-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0022_alter_insuree_kebele_id_alter_insuree_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='employment_type',
            field=models.CharField(blank=True, db_column='EmployerType', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=500, null=True),
        ),
    ]
