# Generated by Django 4.2.16 on 2024-11-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0025_insureeattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='household_address',
            field=models.CharField(blank=True, db_column='HouseholdAddress', max_length=200, null=True),
        ),
    ]
